service: lifehakk-group-project
useDotenv: true
plugins:
  - serverless-python-requirements
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-west-1
  role: arn:aws:iam::534900169478:role/kaily_lambda_exec_role

functions:
  execute:
    handler: src/__main__.execute
    events:
      - s3:
          bucket: lifehakk
          event: s3:ObjectCreated:*
          rules:
            - prefix: incoming/
            - suffix: .csv

package:
  exclude:
    - .gitignore
    - .vscode/**
    - node_modules
    - __pycache__
    - data/**
    - .venv/**
    - docker-compose.yml
    - readme.*
    - .pytest_cache/**
    - tests/**